### ISSUE TITLE
Make the `yaml` reader recursive

### ISSUE THREAD

**Issue by sarajuhosova** [fernivy/fernivy#12]
Currently, the `Config` class in `generate.py` only allows for reading `yaml` files which are not recursive. It also does not take quotation marks (`"`) into account. This needs to be fixed for potential future expansion.

This will work:

```yaml
logo_path: path/logo.png
```

But this will not:
```yaml
logo:
    path: "path"
    filename: "logo.png"
```
